# Generated by Django 2.2.6 on 2019-10-22 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_remove_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='end_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
