# Generated by Django 2.1.5 on 2019-10-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-blog_createdTime']},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blogContent',
        ),
    ]
