# Generated by Django 2.1.5 on 2019-10-02 13:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191002_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogContent',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
