# Generated by Django 2.1.5 on 2019-10-03 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191002_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='blogName',
        ),
        migrations.DeleteModel(
            name='readNum',
        ),
    ]
