# Generated by Django 2.1.5 on 2019-10-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191003_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(default='blogImage/default.jpg', upload_to='blogImage'),
        ),
    ]
